### ISSUE TITLE
Readme file is not rendered correctly 

### ISSUE THREAD

**Issue by IvanFilipov** [Angeld55/Object-oriented_programming_FMI#1]
The following picture shows the problem:
![DeepinScreenshot_select-area_20201118010000](https://user-images.githubusercontent.com/15016284/99460937-79e72c00-2939-11eb-83ea-c8dd7a861d6b.png)

**Comment by Angeld55** [comment]
Fixed with commit: 194e9f17edb2d8910902506976aa2c8b34f6f9b7
Thanks!
